---
  - name: Install packages
    hosts: windows
    tasks:  
      - name: install packages from git repo
        win_chocolatey:
          name: Abra
        environment:
          - chocolateyDownloadUrl: "https://github.com/raam-infi/Chocolatey-powershell/blob/main/chikity/packages/abra.0.1.0.nupkg"
